# Generated by Django 4.1 on 2024-04-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = []
