# Generated by Django 4.1 on 2024-04-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_auto_20240425_1525"),
    ]

    operations = []
