# Generated by Django 4.1 on 2024-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_auto_20240430_1416"),
    ]

    operations = []
