# Generated by Django 4.1 on 2024-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_auto_20240430_1433"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookcategory",
            old_name="category_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="bookcode",
            old_name="code_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="bookcategory",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="bookcode",
            name="code_id",
        ),
        migrations.AlterField(
            model_name="bookcategory",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="bookcode",
            name="id",
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
