# Generated by Django 4.1 on 2024-04-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_rename_category_name_bookcategory_name_and_more"),
    ]

    operations = []
