# Generated by Django 4.1 on 2024-05-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_auto_20240430_1434"),
    ]

    operations = []
