# Generated by Django 4.1 on 2024-05-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_auto_20240501_1806"),
    ]

    operations = []
