# Generated by Django 4.1 on 2024-05-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_auto_20240501_1812"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookcategory",
            old_name="name",
            new_name="category_name",
        ),
        migrations.RenameField(
            model_name="bookcode",
            old_name="name",
            new_name="code_name",
        ),
        migrations.AddField(
            model_name="bookcategory",
            name="category_id",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookcode",
            name="code_id",
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
