# Generated by Django 4.1 on 2024-05-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_rename_name_bookcategory_category_name_and_more"),
    ]

    operations = []
